Update qlik-sense.php to load js at end of body
A change to the qlik-sense.php file to ensure that wordpress can do its things first. The enqueuing priority for qlik-sense resources is set to 20. And the scripts are enqueued to be loaded in the body tag instead of the head. This gets rid of the following errors:
1. Uncaught TypeError: qlik.setOnError is not a function
2. Uncaught Error: Mismatched anonymous define() module: function ($) { 	'use strict'; ...